/**
 * Auto-generated by hub-codegen toolchain
 * DO NOT EDIT MANUALLY
 *
 * Toolchain:
 *   - synapse-cc v0.3.1
 *   - synapse v0.2.0.0
 *   - hub-codegen v0.2.0
 *
 * Backend: locus
 */

// === Core Transport Types ===
// These types define the wire format for all plexus streaming responses.

/** Metadata applied by the caller when wrapping activation responses */
export interface StreamMetadata {
  /** Call path through the system (e.g., ["plexus", "health"]) */
  provenance: string[];
  /** Hash of plexus configuration for cache invalidation */
  plexusHash: string;
  /** Unix timestamp (seconds) when the event was wrapped */
  timestamp: number;
}

/** Data payload with caller-applied metadata */
export interface PlexusStreamItemData {
  type: 'data';
  /** Metadata from calling layer */
  metadata: StreamMetadata;
  /** Type identifier for deserialization (e.g., "health.status") */
  contentType: string;
  /** The actual payload (serialized activation event) */
  content: unknown;
}

/** Progress update during long-running operations */
export interface PlexusStreamItemProgress {
  type: 'progress';
  /** Metadata from calling layer */
  metadata: StreamMetadata;
  /** Human-readable progress message */
  message: string;
  /** Optional completion percentage (0.0 - 100.0) */
  percentage?: number;
}

/** Error occurred during processing */
export interface PlexusStreamItemError {
  type: 'error';
  /** Metadata from calling layer */
  metadata: StreamMetadata;
  /** Human-readable error message */
  message: string;
  /** Optional error code for programmatic handling */
  code?: string;
  /** Whether the operation can be retried */
  recoverable: boolean;
}

/** Stream completed successfully */
export interface PlexusStreamItemDone {
  type: 'done';
  /** Metadata from calling layer */
  metadata: StreamMetadata;
}

/** Server-to-client request for bidirectional communication */
export interface PlexusStreamItemRequest {
  type: 'request';
  /** Unique identifier for correlating response */
  requestId: string;
  /** Serialized request data */
  requestData: StandardRequest;
  /** Maximum time to wait for response (milliseconds) */
  timeoutMs: number;
}

/** Universal stream item - all activations emit this type */
export type PlexusStreamItem =
  | PlexusStreamItemData
  | PlexusStreamItemProgress
  | PlexusStreamItemError
  | PlexusStreamItemDone
  | PlexusStreamItemRequest;

export function isPlexusStreamItemData(e: PlexusStreamItem): e is PlexusStreamItemData { return e.type === 'data'; }
export function isPlexusStreamItemProgress(e: PlexusStreamItem): e is PlexusStreamItemProgress { return e.type === 'progress'; }
export function isPlexusStreamItemError(e: PlexusStreamItem): e is PlexusStreamItemError { return e.type === 'error'; }
export function isPlexusStreamItemDone(e: PlexusStreamItem): e is PlexusStreamItemDone { return e.type === 'done'; }
export function isPlexusStreamItemRequest(e: PlexusStreamItem): e is PlexusStreamItemRequest { return e.type === 'request'; }

// === Bidirectional Communication Types ===

/** Confirmation request (yes/no) */
export interface StandardRequestConfirm {
  type: 'confirm';
  /** Message to display to user */
  message: string;
  /** Default value if user doesn't respond */
  default?: boolean;
}

/** Text prompt request */
export interface StandardRequestPrompt {
  type: 'prompt';
  /** Message to display to user */
  message: string;
  /** Default value */
  default?: string;
  /** Placeholder text */
  placeholder?: string;
}

/** Selection request (single or multiple choice) */
export interface StandardRequestSelect {
  type: 'select';
  /** Message to display to user */
  message: string;
  /** Available options */
  options: SelectOption[];
  /** Allow multiple selections */
  multiSelect?: boolean;
}

/** Standard request types for common UI patterns */
export type StandardRequest =
  | StandardRequestConfirm
  | StandardRequestPrompt
  | StandardRequestSelect;

export function isStandardRequestConfirm(e: StandardRequest): e is StandardRequestConfirm { return e.type === 'confirm'; }
export function isStandardRequestPrompt(e: StandardRequest): e is StandardRequestPrompt { return e.type === 'prompt'; }
export function isStandardRequestSelect(e: StandardRequest): e is StandardRequestSelect { return e.type === 'select'; }

/** Option in a select menu */
export interface SelectOption {
  /** Value returned when selected */
  value: string;
  /** Display label */
  label: string;
  /** Optional description */
  description?: string;
}

/** Response to confirmation request */
export interface StandardResponseConfirmed {
  type: 'confirmed';
  value: boolean;
}

/** Response to prompt request */
export interface StandardResponseText {
  type: 'text';
  value: string;
}

/** Response to select request */
export interface StandardResponseSelected {
  type: 'selected';
  values: string[];
}

/** User cancelled the request */
export interface StandardResponseCancelled {
  type: 'cancelled';
}

/** Standard response types for bidirectional requests */
export type StandardResponse =
  | StandardResponseConfirmed
  | StandardResponseText
  | StandardResponseSelected
  | StandardResponseCancelled;

export function isStandardResponseConfirmed(e: StandardResponse): e is StandardResponseConfirmed { return e.type === 'confirmed'; }
export function isStandardResponseText(e: StandardResponse): e is StandardResponseText { return e.type === 'text'; }
export function isStandardResponseSelected(e: StandardResponse): e is StandardResponseSelected { return e.type === 'selected'; }
export function isStandardResponseCancelled(e: StandardResponse): e is StandardResponseCancelled { return e.type === 'cancelled'; }

/** Respond to a bidirectional request */
export interface PlexusResponse {
  requestId: string;
  response: StandardResponse;
}

/** Error thrown when a PlexusStreamItemError is received */
export class PlexusError extends Error {
  readonly code: string | undefined;
  readonly recoverable: boolean;
  readonly metadata: StreamMetadata | undefined;
  constructor(
    message: string,
    code?: string,
    recoverable: boolean = false,
    metadata?: StreamMetadata
  ) {
    super(message);
    this.name = 'PlexusError';
    this.code = code;
    this.recoverable = recoverable;
    this.metadata = metadata;
  }
}


// Domain types are exported from their respective namespace modules
// Import as: import { TypeName } from './namespace/types'