// Auto-generated by hub-codegen
// Do not edit manually

/** Render progress update */
export interface RenderEventRenderProgress {
  type: 'render_progress';
  elapsedSecs: number;
  framesWritten: number;
  percent: number;
}

/** Render completed successfully */
export interface RenderEventRenderComplete {
  type: 'render_complete';
  bytes: number;
  durationSecs: number;
  frameCount: number;
  outputPath: string;
}

/** Preview frame at timestamp */
export interface RenderEventPreviewFrame {
  type: 'preview_frame';
  content: string;
  height: number;
  time: number;
  width: number;
}

/** Recording metadata */
export interface RenderEventRecordingInfo {
  type: 'recording_info';
  durationSecs: number;
  layoutEvents: number;
  paneCount: number;
  recordingId: string;
}

/** Something went wrong */
export interface RenderEventError {
  type: 'error';
  message: string;
}

/** Events for render operations */
export type RenderEvent = RenderEventRenderProgress | RenderEventRenderComplete | RenderEventPreviewFrame | RenderEventRecordingInfo | RenderEventError;

export function isRenderEventRenderProgress(e: RenderEvent): e is RenderEventRenderProgress { return e.type === 'render_progress'; }
export function isRenderEventRenderComplete(e: RenderEvent): e is RenderEventRenderComplete { return e.type === 'render_complete'; }
export function isRenderEventPreviewFrame(e: RenderEvent): e is RenderEventPreviewFrame { return e.type === 'preview_frame'; }
export function isRenderEventRecordingInfo(e: RenderEvent): e is RenderEventRecordingInfo { return e.type === 'recording_info'; }
export function isRenderEventError(e: RenderEvent): e is RenderEventError { return e.type === 'error'; }
