// Auto-generated by hub-codegen
// Do not edit manually

/** Result of a single operation in a batch */
export interface BatchEntry {
  command: string;
  output?: string | null;
  pane: PaneId;
  success: boolean;
}

/** Session listing result */
export interface LocusEventSessions {
  type: 'sessions';
  sessions: Session[];
}

/** Tab listing result */
export interface LocusEventTabs {
  type: 'tabs';
  tabs: Tab[];
}

/** Pane listing result */
export interface LocusEventPanes {
  type: 'panes';
  panes: Pane[];
}

/** A pane was created */
export interface LocusEventPaneCreated {
  type: 'pane_created';
  pane: Pane;
}

/** A tab was created */
export interface LocusEventTabCreated {
  type: 'tab_created';
  initialPane: PaneId | null;
  tab: Tab;
}

/** A session was created */
export interface LocusEventSessionCreated {
  type: 'session_created';
  session: Session;
}

/** Screen content captured from a pane */
export interface LocusEventScreenCapture {
  type: 'screen_capture';
  content: string;
  lines: number;
  pane: PaneId;
}

/** Layout dumped */
export interface LocusEventLayout {
  type: 'layout';
  content: string;
}

/** A command was launched in a pane */
export interface LocusEventCommandLaunched {
  type: 'command_launched';
  command: string;
  pane: PaneId;
}

/** A command was executed in an existing pane and confirmed running */
export interface LocusEventCommandStarted {
  type: 'command_started';
  capture: string | null;
  command: string;
  pane: PaneId;
}

/** A command ran and exited */
export interface LocusEventCommandExited {
  type: 'command_exited';
  capture: string | null;
  command: string;
  exitCode: number | null;
  pane: PaneId;
}

/** Input was sent to a pane */
export interface LocusEventInputSent {
  type: 'input_sent';
  chars: number;
  pane: PaneId;
}

/** A grid layout was created with multiple panes */
export interface LocusEventLayoutCreated {
  type: 'layout_created';
  cols: number;
  panes: Pane[];
  rows: number;
  tab: TabId;
}

/** Batch results from multiple pane operations */
export interface LocusEventBatchResult {
  type: 'batch_result';
  results: BatchEntry[];
}

/** Screen diff after sending a command to a foreign shell */
export interface LocusEventScreenDiff {
  type: 'screen_diff';
  afterLines: number;
  beforeLines: number;
  newContent: string;
  pane: PaneId;
}

/** Screen content from terminal state (instant, no file I/O) */
export interface LocusEventScreenContent {
  type: 'screen_content';
  contents: string;
  pane: PaneId;
}

/** Screen content changed (event-driven notification) */
export interface LocusEventScreenChanged {
  type: 'screen_changed';
  contents: string;
  pane: PaneId;
  sequence: number;
}

/** Cursor position */
export interface LocusEventCursorPosition {
  type: 'cursor_position';
  col: number;
  pane: PaneId;
  row: number;
}

/** Region content (specific rows) */
export interface LocusEventRegionContent {
  type: 'region_content';
  content: string;
  pane: PaneId;
}

/** Terminal dimensions */
export interface LocusEventDimensions {
  type: 'dimensions';
  height: number;
  pane: PaneId;
  width: number;
}

/** No changes since requested sequence */
export interface LocusEventNoChanges {
  type: 'no_changes';
  sequence: number;
}

/** Sequence number update */
export interface LocusEventSequenceUpdate {
  type: 'sequence_update';
  pane: PaneId;
  sequence: number;
}

/** List of tracked panes */
export interface LocusEventTrackedPanes {
  type: 'tracked_panes';
  panes: string[];
}

/** Pane state info list */
export interface LocusEventPaneStateInfos {
  type: 'pane_state_infos';
  infos: PaneStateInfo[];
}

/** Operation timed out */
export interface LocusEventTimeout {
  type: 'timeout';
}

/** Action completed successfully */
export interface LocusEventOk {
  type: 'ok';
  message: string;
}

/** Something went wrong */
export interface LocusEventError {
  type: 'error';
  message: string;
}

export type LocusEvent = LocusEventSessions | LocusEventTabs | LocusEventPanes | LocusEventPaneCreated | LocusEventTabCreated | LocusEventSessionCreated | LocusEventScreenCapture | LocusEventLayout | LocusEventCommandLaunched | LocusEventCommandStarted | LocusEventCommandExited | LocusEventInputSent | LocusEventLayoutCreated | LocusEventBatchResult | LocusEventScreenDiff | LocusEventScreenContent | LocusEventScreenChanged | LocusEventCursorPosition | LocusEventRegionContent | LocusEventDimensions | LocusEventNoChanges | LocusEventSequenceUpdate | LocusEventTrackedPanes | LocusEventPaneStateInfos | LocusEventTimeout | LocusEventOk | LocusEventError;

export function isLocusEventSessions(e: LocusEvent): e is LocusEventSessions { return e.type === 'sessions'; }
export function isLocusEventTabs(e: LocusEvent): e is LocusEventTabs { return e.type === 'tabs'; }
export function isLocusEventPanes(e: LocusEvent): e is LocusEventPanes { return e.type === 'panes'; }
export function isLocusEventPaneCreated(e: LocusEvent): e is LocusEventPaneCreated { return e.type === 'pane_created'; }
export function isLocusEventTabCreated(e: LocusEvent): e is LocusEventTabCreated { return e.type === 'tab_created'; }
export function isLocusEventSessionCreated(e: LocusEvent): e is LocusEventSessionCreated { return e.type === 'session_created'; }
export function isLocusEventScreenCapture(e: LocusEvent): e is LocusEventScreenCapture { return e.type === 'screen_capture'; }
export function isLocusEventLayout(e: LocusEvent): e is LocusEventLayout { return e.type === 'layout'; }
export function isLocusEventCommandLaunched(e: LocusEvent): e is LocusEventCommandLaunched { return e.type === 'command_launched'; }
export function isLocusEventCommandStarted(e: LocusEvent): e is LocusEventCommandStarted { return e.type === 'command_started'; }
export function isLocusEventCommandExited(e: LocusEvent): e is LocusEventCommandExited { return e.type === 'command_exited'; }
export function isLocusEventInputSent(e: LocusEvent): e is LocusEventInputSent { return e.type === 'input_sent'; }
export function isLocusEventLayoutCreated(e: LocusEvent): e is LocusEventLayoutCreated { return e.type === 'layout_created'; }
export function isLocusEventBatchResult(e: LocusEvent): e is LocusEventBatchResult { return e.type === 'batch_result'; }
export function isLocusEventScreenDiff(e: LocusEvent): e is LocusEventScreenDiff { return e.type === 'screen_diff'; }
export function isLocusEventScreenContent(e: LocusEvent): e is LocusEventScreenContent { return e.type === 'screen_content'; }
export function isLocusEventScreenChanged(e: LocusEvent): e is LocusEventScreenChanged { return e.type === 'screen_changed'; }
export function isLocusEventCursorPosition(e: LocusEvent): e is LocusEventCursorPosition { return e.type === 'cursor_position'; }
export function isLocusEventRegionContent(e: LocusEvent): e is LocusEventRegionContent { return e.type === 'region_content'; }
export function isLocusEventDimensions(e: LocusEvent): e is LocusEventDimensions { return e.type === 'dimensions'; }
export function isLocusEventNoChanges(e: LocusEvent): e is LocusEventNoChanges { return e.type === 'no_changes'; }
export function isLocusEventSequenceUpdate(e: LocusEvent): e is LocusEventSequenceUpdate { return e.type === 'sequence_update'; }
export function isLocusEventTrackedPanes(e: LocusEvent): e is LocusEventTrackedPanes { return e.type === 'tracked_panes'; }
export function isLocusEventPaneStateInfos(e: LocusEvent): e is LocusEventPaneStateInfos { return e.type === 'pane_state_infos'; }
export function isLocusEventTimeout(e: LocusEvent): e is LocusEventTimeout { return e.type === 'timeout'; }
export function isLocusEventOk(e: LocusEvent): e is LocusEventOk { return e.type === 'ok'; }
export function isLocusEventError(e: LocusEvent): e is LocusEventError { return e.type === 'error'; }

export interface Pane {
  command?: string | null;
  cwd?: string | null;
  floating: boolean;
  focused: boolean;
  id: PaneId;
  name?: string | null;
  session: SessionId;
  tab: TabId;
}

/** Logical pane identifier. Assigned by Locus, not the backend.
Backends map this to their native pane ID internally. */
export type PaneId = string;

/** Information about a pane's state */
export interface PaneStateInfo {
  height: number;
  paneId: string;
  sequence: number;
  width: number;
}

export interface Session {
  attached: boolean;
  id: SessionId;
  name: string;
  panes: number;
  tabs: number;
}

/** Session identifier. */
export type SessionId = string;

export interface Tab {
  focused: boolean;
  id: TabId;
  index: number;
  name?: string | null;
  paneCount: number;
  session: SessionId;
}

/** Logical tab identifier. */
export type TabId = string;
