// Auto-generated by hub-codegen
// Do not edit manually

/** Recording started successfully */
export interface RecordingEventRecordingStarted {
  type: 'recording_started';
  outputDir: string;
  paneCount: number;
  recordingId: string;
}

/** Recording stopped successfully */
export interface RecordingEventRecordingStopped {
  type: 'recording_stopped';
  castFiles: string[];
  durationSecs: number;
  layoutFile: string;
  recordingId: string;
}

/** Recording status */
export interface RecordingEventRecordingStatus {
  type: 'recording_status';
  active: boolean;
  elapsedSecs: number;
  outputDir: string | null;
  paneIds: string[];
  recordingId: string | null;
}

/** List of recordings */
export interface RecordingEventRecordings {
  type: 'recordings';
  recordings: RecordingInfo[];
}

/** Action completed successfully */
export interface RecordingEventOk {
  type: 'ok';
  message: string;
}

/** Something went wrong */
export interface RecordingEventError {
  type: 'error';
  message: string;
}

/** Events for recording operations */
export type RecordingEvent = RecordingEventRecordingStarted | RecordingEventRecordingStopped | RecordingEventRecordingStatus | RecordingEventRecordings | RecordingEventOk | RecordingEventError;

export function isRecordingEventRecordingStarted(e: RecordingEvent): e is RecordingEventRecordingStarted { return e.type === 'recording_started'; }
export function isRecordingEventRecordingStopped(e: RecordingEvent): e is RecordingEventRecordingStopped { return e.type === 'recording_stopped'; }
export function isRecordingEventRecordingStatus(e: RecordingEvent): e is RecordingEventRecordingStatus { return e.type === 'recording_status'; }
export function isRecordingEventRecordings(e: RecordingEvent): e is RecordingEventRecordings { return e.type === 'recordings'; }
export function isRecordingEventOk(e: RecordingEvent): e is RecordingEventOk { return e.type === 'ok'; }
export function isRecordingEventError(e: RecordingEvent): e is RecordingEventError { return e.type === 'error'; }

/** Information about a past recording */
export interface RecordingInfo {
  createdAt?: number | null;
  hasLayout: boolean;
  outputDir: string;
  paneCount: number;
  recordingId: string;
}
