// Auto-generated by hub-codegen
// Do not edit manually

/** A pane reference — either a name or a %id. Must be resolved via
`backend.resolve_pane()` before use. This type enforces that callers
go through resolution rather than passing raw strings. */
export type PaneRef = string;
